In [1]:
# auto reimport magic cell
%load_ext autoreload
%autoreload 2

In [17]:
import generic_kalman_filtering_class as kulman
import numpy as np
import test_kalman_filter as test_km
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import pandas as pd

In [3]:
file_path = "ground_truth.txt"
with open(file_path, "r") as txt_file:
    with open("ground_truth.csv", "w") as csv_file:
        csv_file.write("time_step,ped_id,x,y\n")
        for line in txt_file:
            csv_file.write(line.replace("\t", ","))

In [4]:
gt_df = pd.read_csv("ground_truth.csv")
gt_df

time_step  ped_id      x     y
0           780     1.0   8.46  3.59
1           790     1.0   9.57  3.79
2           800     1.0  10.67  3.99
3           800     2.0  13.64  5.80
4           810     1.0  11.73  4.32
...         ...     ...    ...   ...
5487      12380   358.0  10.35  6.75
5488      12380   364.0  12.29  4.14
5489      12380   365.0  12.65  5.35
5490      12380   366.0  12.08  7.02
5491      12380   367.0  11.20  8.44

[5492 rows x 4 columns]

In [16]:
tracker = kulman.KalmanTracker("config.py")
timesteps = gt_df["time_step"].sort_values().unique()
timesteps
noise_std_dev = 0.5
previous_values = None
i = 0
for time_step in timesteps:
    if previous_values is not None:
        previous_values = gt_df[gt_df["time_step"] == time_step]
        continue
    current_values = gt_df[gt_df["time_step"] == time_step]
    x, y = current_values["x"].values, current_values["y"].values
    noisy_x, noisy_y = test_km.add_noise(x, y, 0.4)
    measurements = np.array([noisy_x, noisy_y]).T
    pedestriant_states = tracker.update_pedestrian_tracking(measurements)
    print("Pedestrian States:\n", pedestriant_states)
    print("Measurements:\n", measurements)
    print("GT:\n", current_values)

# current_time_step = -1
# for time_step, ped_id, x, y in ground_truth_data:
#     if time_step != current_time_step:
#         # Update tracker with previous time step's measurements
#         if current_time_step >= 0:
#             tracked_pedestrians = tracker.update_pedestrian_tracking(measurements)
#             print(f"Time step: {current_time_step}")
#             print("Tracked pedestrians:", tracked_pedestrians)
#             print()

#         current_time_step = time_step
#         measurements = []

#     # Add noise to ground truth data
#     noisy_x, noisy_y = add_noise(x, y, noise_std_dev)
#     measurements.append(np.array([noisy_x, noisy_y]))

Pedestrian States:
 {'1': array([8.43312136, 3.63426067, 0.        , 0.        ])}
Measurements:
 [[8.43312136 3.63426067]]
GT:
    time_step  ped_id     x     y
0        780     1.0  8.46  3.59
Pedestrian States:
 {'1': array([10.34370966,  3.95206359,  0.95524639,  0.15889352])}
Measurements:
 [[10.35326213  3.95365253]]
GT:
    time_step  ped_id     x     y
1        790     1.0  9.57  3.79
Pedestrian States:
 {'1': array([10.38401552,  3.7036592 ,  0.06661044, -0.23669456]), '2': array([13.33650846,  5.5058657 ,  0.        ,  0.        ])}
Measurements:
 [[10.36650846  3.6958657 ]
 [13.33650846  5.5058657 ]]
GT:
    time_step  ped_id      x     y
2        800     1.0  10.67  3.99
3        800     2.0  13.64  5.80
Pedestrian States:
 {'1': array([11.76939733,  4.19768523,  0.85062287,  0.19772041]), '2': array([12.40908217,  5.77872286, -0.46368996,  0.13642176])}
Measurements:
 [[12.04444527  4.35008708]
 [12.40444527  5.78008708]]
GT:
    time_step  ped_id      x     y
4        810

In [18]:
measurements[0]

array([9.86951189, 5.95953901])